appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: lU7rncfABTVGF6RmY9L6n67lrTDVbvxHHnIdXPodeniIwJX5g7x9W5gmIvq9rgFqAStGPzIb08/KFX4NEszOgNWjMyzapu+c5QMZi4I2zzj5eLPz9QEZwNG5K8T2Oa7q8t81g8an8+PlwV07dNJPSZoGzzY2HhnWzK9QaLrWrO/0aPaJ5GpcttScBOf4QJ0XcEL/mss/JHKthOYCwFsdKApUAn0Yr0rIlK8AkX+vIKROyQj/6bUo8B+ejZrdv218fwyeFGubvb0dw6RfyF9zVLISiKw5Bhm6mgN/IKM99zw2zyOeC+yPYEhU2UXx2yqIVWKkuyWHG9Z7Je4j75QcATwTQi2DagW/2xGmHDMGsun2FcLCMW1y6O6sh2MSvD8712uPL1ZhNTvivdOMWv1aFNG5BlSaSKjF37ogAwNue69bDNXdm868vvIXPzCdrX5zn5wilBCTsQKbukiyhaJehfg8MCxD0dr84wKr9Wp9eQAzLTou66T7BNjJwD+qu54ewS5++jbw6a9iqUEgwEJ3hPZQ44aE8K++IVW4pyLHSOuxt2GcpnZ+Fh6eOh+VQNMzGA9O+ACntvX3skyTOBFPO/j/M6rXZTyjjuFoShpjzzudTI7lLpFMIpq56ofdtvsuAjnQGeBxMAZmgntgreWQcGExI3lyKnsK/0XrBVcBhw4=}
conda_forge_output_validation: true
